import { Theme } from "../theme.slint";
import { CursorGlyph } from "./cursor-glyph.slint";

export component AppWindow inherits Window {
    background: Theme.bg;
    default-font-family: "DejaVu Sans Mono";
    default-font-size: Theme.font-body;

    cursor-tracker := TouchArea {
        width: 100%;
        height: 100%;
        mouse-cursor: none;
        @children
    }

    CursorGlyph {
        pos-x: cursor-tracker.mouse-x;
        pos-y: cursor-tracker.mouse-y;
    }
}